language:
  - cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y cmake git mesa-utils freeglut3-dev libxmu-dev libxi-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
